@startuml

title "RDMO Docker Compose Setup"

rectangle {
    actor "User" as user
    frame Volumes {
        storage "log:/vol/log" as vlog
        storage "rdmoapp:/vol/rdmo-app" as vapp
        storage "postgres:/var/lib/postgresql/data" as vpg
    }
    frame Containers {
        agent "RDMO\n--\nrunning gunicorn" as rdmo
        agent "Caddy\n--\nlistening on 8484:8080\neither serve static\nor pass to rdmo" as caddy
        agent "PostgreSQL\n--\nstoring data in the volume" as pg
    }
    <style>
    arrow {
        FontSize 14
        LineColor #000000
    }
    agent {
        BackGroundColor #D8B26C
        LineThickness 2
    }
    storage {
        BackGroundColor #99B29C
        LineThickness 2
    }
    frame {
        BackGroundColor #eeeeee
    }
    </style>
}

user <..> caddy : " http"

rdmo -- vapp
rdmo -->  vlog
caddy -- vapp : "static file access"
caddy --> vlog
caddy <.l.> rdmo : "http"
pg -- vpg
rdmo <..> pg : " psql"

@enduml
