FROM debian:stable

ARG UID=<UID>
ENV USER=nginx

RUN apt update && apt upgrade -y && apt install -y \
        nginx \
        curl \
    && rm -rf /var/lib/apt/lists/*

RUN rm -rf /etc/nginx/sites-enabled
COPY ./rootfs /

RUN useradd -m -u ${UID} -s /bin/bash "${USER}"

CMD ["/drun.sh"]
