FROM debian:stable

ARG UID=<UID>
ENV USER=rdmo

ARG DEBIAN_FRONTEND=noninteractive

ENV PATH=/opt:${PATH}

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN apt update && apt upgrade -y && apt install -y \
        python3 \
        python3-dev \
        python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install virtualenv

RUN apt update && apt-get install -y \
        locales \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8

# build dependencies
RUN apt update && apt install -y \
        build-essential \
        curl \
        git \
        libxml2-dev \
        libxslt-dev \
        zlib1g-dev \
        procps \
        vim \
    && rm -rf /var/lib/apt/lists/*

# postgres
RUN apt update && apt install -y \
        libpq-dev \
        postgresql \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# for document export
RUN apt update && apt install -y \
        pandoc \
        texlive-xetex \
    && rm -rf /var/lib/apt/lists/*

COPY ./rootfs /
RUN chmod -R 777 /tmp

RUN useradd -m -u ${UID} -s /bin/bash "${USER}"
RUN chown "${USER}:${USER}" "/home/${USER}"

USER "${USER}"
CMD ["/drun.sh"]
