FROM debian:10

ARG UID=<UID>
ENV USER=rdmo

ENV PATH=/opt:${PATH}

RUN apt update -y && apt upgrade -y && apt install -y \
    python3 \
    python3-dev \
    python3-pip \
 && pip3 install virtualenv

# build dependencies
RUN apt install -y \
    build-essential \
    curl \
    git \
    libxml2-dev \
    libxslt-dev \
    zlib1g-dev \
    procps \
    vim

# postgres
RUN apt install -y \
    libpq-dev \
    postgresql \
    postgresql-client \
    python-psycopg2

# for document export
RUN apt install -y \
    pandoc \
    texlive-xetex

COPY ./rootfs /
RUN chmod -R 777 /tmp

RUN useradd -m -u ${UID} -s /bin/bash "${USER}"
RUN chown "${USER}:${USER}" "/home/${USER}"

USER "${USER}"
CMD ["/drun.sh"]
