FROM httpd:latest

ARG UID=<UID>

ENV HTTPD_CONF="/usr/local/apache2/conf/httpd.conf"

RUN apt update -y && apt install -y \
    curl \
    python-psycopg2 \
    libexpat1  \
    apache2-utils \
    ssl-cert \
    python3 \
    python3-dev \
    python3-pip \
    libapache2-mod-wsgi-py3 \
    pandoc \
    texlive-xetex

RUN echo "LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so" >> ${HTTPD_CONF} \
 && echo "IncludeOptional conf.d/*.conf" >> ${HTTPD_CONF}

RUN mkdir -p /usr/local/apache2/conf.d
COPY vhosts.conf /usr/local/apache2/conf.d/vhosts.conf

RUN useradd -m -u $UID -s /bin/bash rdmo
RUN mkdir -p /var/www/html
RUN mkdir -p /var/run/apache2

HEALTHCHECK --timeout=10s --interval=20s --retries=3 \
   CMD curl -f http://localhost:80 || exit 1
